name: 'IONOS-Deploy'
description: 'Deploy content to IONOS webspace'
inputs:
  service-host:
    description: 'The service endpoint to call in the action'
    required: true
  api-key:
    description: 'The api key to access IONOS Deploy Now'
    required: true
  project-id:
    description: 'The identifier of the IONOS Deploy Now project'
    required: true
  branch-id:
    description: 'The identifier of a branch'
    required: true
  deployment-id:
    description: 'The identifier of a deployment'
    required: true
  deployment-folder:
    description: 'The folder to deploy'
    required: true
    default: deployment
  deployment-info:
    description: 'A json object containing information about the deployment'
    required: true
  ssh-user:
    description: 'The SSH user for the deployment'
    required: true
  ssh-key:
    description: 'The SSH key for the deployment'
    required: true

  workspace:
    default: "'${{ github.workspace }}/'"
runs:
  using: 'docker'
  image: 'docker://ghcr.io/ionos-deploy-now/deploy-to-ionos:v2.0.1'
  env:
    SERVICE_HOST: ${{ inputs.service-host }}
    API_KEY: ${{ inputs.api-key }}
    PROJECT_ID: ${{ inputs.project-id }}
    BRANCH_ID: ${{ inputs.branch-id }}
    DEPLOYMENT_ID: ${{ inputs.deployment-id }}
    DEPLOYMENT_FOLDER: ${{ inputs.deployment-folder }}
    DEPLOYMENT_INFO: ${{ inputs.deployment-info }}
    SSH_USER: ${{ inputs.ssh-user }}
    SSH_KEY: ${{ inputs.ssh-key }}
