name: 'IONOS-Deploy'
description: 'Deploy content to IONOS webspace'
inputs:
  service-host:
    description: 'The host of the IONOS Deploy Now API to retrieve necessary data about the current project'
    required: true
  api-key:
    description: 'API Key used for authentication and authorization of the IONOS Deploy Now API'
    required: true
  project:
    description: 'IONOS Deploy Now projectId, used to identify current project for which data is retrieved'
    required: true
  branch-id:
    description: 'IONOS Deploy Now branchId, used to identify current branch of the project for which data is retrieved'
    required: true
  dist-folder:
    description: 'Root directory which is deployed to the IONOS infrastructure'
    required: true
  bootstrap-deploy:
    description: 'Executes the bootstrap deployment block if this is the first build of a branch'
    required: true
    default: 'true'
  remote-host:
    description: 'Target in the IONOS infrastructure for deployment'
    required: true
  storage-quota:
    description: 'The max allowed storage quota on the IONOS infrastructure for this project/branch'
    required: true
runs:
  using: 'docker'
  image: 'docker://ghcr.io/ionos-deploy-now/deploy-to-ionos:feature-pre-and-post-remote-commands'
  env:
    SERVICE_HOST: ${{ inputs.service-host }}
    API_KEY: ${{ inputs.api-key }}
    PROJECT_ID: ${{ inputs.project }}
    BRANCH_ID: ${{ inputs.branch-id }}
    DIST_FOLDER: ${{ inputs.dist-folder }}
    BOOTSTRAP_DEPLOY: ${{ inputs.bootstrap-deploy }}
    REMOTE_HOST: ${{ inputs.remote-host }}
    STORAGE_QUOTA: ${{ inputs.storage-quota }}
