name: 'IONOS-Deploy'
description: 'Deploy content to IONOS webspace'
inputs:
  service-host:
    description: 'The host of the IONOS Deploy Now API to retrieve necessary data about the current project'
    required: true
  api-key:
    description: 'API Key used for authentication and authorization of the IONOS Deploy Now API'
    required: true
  project:
    description: 'IONOS Deploy Now projectId, used to identify current project for which data is retrieved'
    required: true
  branch-id:
    description: 'IONOS Deploy Now branchId, used to identify current branch of the project for which data is retrieved'
    required: true
  dist-folder:
    description: 'Root directory which is deployed to the IONOS infrastructure'
    required: true
  runtime-placeholder-files:
    description: 'Files that contain runtime placeholders'
    required: false
  bootstrap-deploy:
    description: 'Deprecated. This value is no longer used by the action. We just keep it to prevent github form showing warnings for existing projects which still pass those values'
    required: false
  remote-host:
    description: 'Deprecated. This value is no longer used by the action. We just keep it to prevent github form showing warnings for existing projects which still pass those values'
    required: false
  storage-quota:
    description: 'Deprecated. This value is no longer used by the action. We just keep it to prevent github form showing warnings for existing projects which still pass those values'
    required: false
runs:
  using: 'docker'
  image: 'docker://ghcr.io/ionos-deploy-now/deploy-to-ionos:v1.1.1'
  env:
    SERVICE_HOST: ${{ inputs.service-host }}
    API_KEY: ${{ inputs.api-key }}
    PROJECT_ID: ${{ inputs.project }}
    BRANCH_ID: ${{ inputs.branch-id }}
    DIST_FOLDER: ${{ inputs.dist-folder }}
    RUNTIME_PLACEHOLDER_FILES: ${{ inputs.runtime-placeholder-files }}
